openapi: 3.0.3
info:
  title: Category API
  description: API for managing categories, including creation, retrieval, updating, and deletion.
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
    description: Local development server
paths:
  /categories:
    get:
      summary: Get all categories
      description: Retrieve a list of all categories.
      tags:
        - Categories
      responses:
        "200":
          description: A list of categories.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        "500":
          description: Internal server error.
    post:
      summary: Create a new category
      description: Add a new category to the system.
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryInput"
      responses:
        "201":
          description: Category created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          description: Validation error.
        "500":
          description: Internal server error.
  /categories/{id}:
    get:
      summary: Get a category by ID
      description: Retrieve a specific category by its unique ID.
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the category.
      responses:
        "200":
          description: Category retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "404":
          description: Category not found.
        "500":
          description: Internal server error.
    put:
      summary: Update a category
      description: Update the details of a specific category.
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the category.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryInput"
      responses:
        "200":
          description: Category updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          description: Validation error.
        "404":
          description: Category not found.
        "500":
          description: Internal server error.
    delete:
      summary: Delete a category
      description: Remove a specific category from the system by its unique ID.
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The unique ID of the category.
      responses:
        "204":
          description: Category deleted successfully.
        "404":
          description: Category not found.
        "500":
          description: Internal server error.
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the category.
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          description: The name of the category.
          example: "Programming"
        is_for_student:
          type: boolean
          description: Indicates if the category is for students.
          example: true
        is_for_tutor:
          type: boolean
          description: Indicates if the category is for tutors.
          example: false
        is_required:
          type: boolean
          description: Indicates if the category is required.
          example: true
    CategoryInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: The name of the category.
          example: "Programming"
        is_for_student:
          type: boolean
          description: Indicates if the category is for students.
          example: true
        is_for_tutor:
          type: boolean
          description: Indicates if the category is for tutors.
          example: false
        is_required:
          type: boolean
          description: Indicates if the category is required.
          example: true
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message.
          example: "Category with ID 123 not found."
